name: ai_photo_enhancer

description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '^3.11.0'

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.1.2
  http: ^1.2.2
  path_provider: ^2.1.4